services:
  user-api:
    container_name: user-api
    build:
      context: ./src/users
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DB_HOST=user-db
    depends_on:
      - user-db

  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: user_secret
      MYSQL_DATABASE: user_database
    volumes:
      - user_db_data:/var/lib/mysql

  product-api:
    container_name: product-api
    build:
      context: ./src/products
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - DB_HOST=product-db
    depends_on:
      - product-db

  product-db:
    image: mysql:8.0
    container_name: product-db
    environment:
      MYSQL_ROOT_PASSWORD: product_secret
      MYSQL_DATABASE: product_database
    volumes:
      - product_db_data:/var/lib/mysql

  order-api:
    container_name: order-api
    build:
      context: ./src/orders
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - DB_HOST=order-db
    depends_on:
      - order-db

  order-db:
    image: mysql:8.0
    container_name: order-db
    environment:
      MYSQL_ROOT_PASSWORD: order_secret
      MYSQL_DATABASE: order_database
    volumes:
      - order_db_data:/var/lib/mysql

volumes:
  user_db_data:
  product_db_data:
  order_db_data: