services:
  user-api:
    container_name: user-api
    build:
      context: ./src
      dockerfile: Dockerfile
    command: node users_app.js
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DB_HOST=user-db
    depends_on:
      - user-db

  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: user_secret
      MYSQL_DATABASE: user_database
    volumes:
      - user_db_data:/var/lib/mysql

  product-api:
    container_name: product-api
    build:
      context: ./src
      dockerfile: Dockerfile
    command: node products_app.js
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - DB_HOST=product-db
    depends_on:
      - product-db

  product-db:
    image: mysql:8.0
    container_name: product-db
    environment:
      MYSQL_ROOT_PASSWORD: product_secret
      MYSQL_DATABASE: product_database
    volumes:
      - product_db_data:/var/lib/mysql


volumes:
  user_db_data:
  product_db_data: